### ISSUE TITLE
Design for advanced GF API config

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive-minisite#33]
I've started to firm up my understanding of the Google Fonts API structure for multi-axis calls.

<img width="1152" alt="recursive-gf_api_config-2019_12_04 (2)" src="https://user-images.githubusercontent.com/45946693/70189463-63f94080-16c1-11ea-895d-d9eb18df9bae.png">

**Open questions:**
- Is it clear what this page is for? If not, what might make it more clear?
- Will users be able to understand this without understanding how variable fonts work? If not, how might we give them enough information to use this?
- If an axis range has only two options, it can't be restricted. Is this obvious yet? How might we clarify that to the user?
- The **Italic** axis can't (currently) be subset, because it only controls alternate glyph substitution. Is it confusing that this config flow leaves it out? Should it be added, with an explanation that it can't be subset?

**Comment by arrowtype** [comment]
Interesting idea worth exploring, from @RoelN:

> Random thought: would it help to step away from sliders (which are associated with “that’s how you control the axes”), and make each range turn-on-and-offable?
> 
> So each part acts like button
> `[          300 - 800        ][  800 - 1000  ]`
> Click the last part, and you turn it off. You get visual feedback that now only 300-800 is left

**Comment by arrowtype** [comment]
## Axis range subsetting

> each part acts like button `[ 300 - 800 ][ 800 - 1000 ]`

Doing this by itself doesn't quite work, because it doesn't make it clear that ranges must be contiguous (this wouldn't actually be a problem for Recursive, but would be an issue for any font with a 4-part axis). So instead, it might make sense to instead take inspiration from [date pickers](https://material.io/components/pickers/#anatomy).

A side benefit is that it becomes more clear how to show a two-stop axis range, which can't be subset but must be shown as fully active.

<img width="894" alt="Frame 1" src="https://user-images.githubusercontent.com/45946693/70280614-ce27e900-1786-11ea-9235-45ff874bdba3.png">

Together, the page design now looks like this:

<img width="1152" alt="recursive-gf_api_config-2019_12_05" src="https://user-images.githubusercontent.com/45946693/70280180-e0555780-1785-11ea-8fd2-63d7f6136b7d.png">

It is designed so that the necessary controls fit onto a fairly small viewport – the above is 1152x755. On a larger screen (such as a 15" MacBook Pro), it would look something like this:

<img width="1440" alt="recursive-gf_api_config-2019_12_04 (4)" src="https://user-images.githubusercontent.com/45946693/70281206-70949c00-1788-11ea-8e4a-64a15df84a22.png">

And a much larger screen might look something like this:

<img width="1975" alt="recursive-gf_api_config-2019_12_04 (5)" src="https://user-images.githubusercontent.com/45946693/70281219-78544080-1788-11ea-984f-9cdf4698ee06.png">

And a much _smaller_ screen might look something like this – assuming we'd skip the previews, because they would probably scale badly and because a mobile API config is probably an edge case:

<img width="299" alt="recursive-gf_api_config-2019_12_05 (2)" src="https://user-images.githubusercontent.com/45946693/70281958-58258100-178a-11ea-9dff-f82f4108f850.png">

## Axis naming & Tooltips

![image](https://user-images.githubusercontent.com/45946693/70280201-ec411980-1785-11ea-8920-369e8a452f67.png)

**Comment by arrowtype** [comment]
Of course, we may not need the big blue across the top, especially because this probably won't have a "download" configurator at first...

<img width="1152" alt="recursive-gf_api_config-2019_12_05 (3)" src="https://user-images.githubusercontent.com/45946693/70283187-5fe72480-178e-11ea-9878-44dba953d384.png">

**Comment by arrowtype** [comment]
Hmm, somehow, the "embed font" section doesn't yet feel like it has the correct placement or treatment. I probably need to make some more very simple sketches to think through whether there's some unexplored territory, here.

**Comment by arrowtype** [comment]
If we remove the blue bar and make the "filesize" info collapsible, we can provide some much-needed space for explanation/help text. I'd still want to keep this quite brief, but it will probably be important to explain that:

- Recursive is hosted on Google Fonts
- This tool is to help users make advanced custom calls for the font

<img width="1152" alt="recursive-gf_api_config-2019_12_05 (1)" src="https://user-images.githubusercontent.com/45946693/70337379-f3fdce00-1818-11ea-9000-44346da2eeaf.png">

**Comment by arrowtype** [comment]
I've briefly explored adding a seconary "download" page, to the design. This page would potentially help people see what options were available in OpenType features and to customize a "RIBBI" static font package for their code editor.

However, this idea has some problems.

- It somewhat mixes "Education" with "Customization," covering both _how to use OpenType features_ and _customizing a RIBBI download_
- It somewhat clashes with what will be available to users via the Google Fonts API. And if this _is_ something that would allow a font to be downloaded for self-hosted use, should it also allow subsetting? If so, then embed & download options should probably be in the _same_ view/sidebar.


<img width="1152" alt="recursive-gf_api_config-2019_12_06" src="https://user-images.githubusercontent.com/45946693/70360095-84550680-184b-11ea-9f63-96775435e37a.png">


It's not as high-priority as the main API config, so it shouldn't be done until the main thing is built. However, I'm exploring it now as a way to better consider the overall design.

**Comment by arrowtype** [comment]
I'm feeling much better about this route: 

- it keeps all configuration and embed info in the sidebar, and preview gets the whole main area of the page 
- it places the filesize information at the top of the "customize" section of the sidebar. That's the point of this subsetting, afterall.
- the "Embed" section goes to the bottom of the sidebar. It includes a "download" icon that links to files which are either customized or standard.

Note: the following mockups are designed for a 15" MBP, to clarify that the "Embed" section sticks to the bottom of the sidebar, while the "Customize" section takes up the top of the sidebar, and will allow scrolling overflow as necessary.

<img width="1440" alt="recursive-gf_api_config-2019_12_06" src="https://user-images.githubusercontent.com/45946693/70364059-f5e78180-1858-11ea-8335-86ff423bc6a1.png">


<img width="1440" alt="recursive-gf_api_config-2019_12_06-1" src="https://user-images.githubusercontent.com/45946693/70364013-bc167b00-1858-11ea-8b7e-f2ad1a50362d.png">

**Comment by arrowtype** [comment]
I've started prototyping this at https://github.com/arrowtype/gf-url-api-configurator

**Comment by arrowtype** [comment]
Having put more thought and conversations into this, I now believe that the two most important views to show will be a "type tester" of the resulting font someone will get from their configuration, plus a grid of "included instances." These may look something like this:

<img width="1440" alt="recursive-gf_api_config-tester-2020_04_10" src="https://user-images.githubusercontent.com/45946693/79000553-d8823700-7b1a-11ea-9eb3-918fec75fa89.png">

<img width="1440" alt="recursive-gf_api_config-instances-2020_04_10" src="https://user-images.githubusercontent.com/45946693/79000567-dcae5480-7b1a-11ea-9947-5ec2c3e14d74.png">

**Comment by davelab6** [comment]
I think the ranged axes should be filled, sorry this is rough:


<img width="1440" alt="79000720-239c4a00-7b1b-11ea-91f3-871f6221491f" src="https://user-images.githubusercontent.com/261579/79009930-bb576380-7b2e-11ea-8d27-162779e424c8.png">

**Comment by davelab6** [comment]
Or rather, maybe its more like this:

<img width="1440" alt="79000720-239c4a00-7b1b-11ea-91f3-871f6221491f (1)" src="https://user-images.githubusercontent.com/261579/79030993-f0cd7280-7b69-11ea-950a-32f6fb1a25b9.png">

**Comment by davelab6** [comment]
> Having put more thought and conversations into this, I now believe that the two most important views to show will be a "type tester" of the resulting font someone will get from their configuration, plus a grid of "included instances."

Cool! I agree that it is very important to **see* the results, as that is ultimately what matters, and also that too much abstract design space mapping/controls are a bad UX because they require too much forethought about the design space. 

For the 'instances' tab, I would expect each `rw` is clickable and turns on/blue to be selected on the sidebar, and off/grey to be unselected; and similarly, selections made in the sidebar will update the state of the `rw`s; and the labels at the left side (for weights) and top (for other axes) would also be hoverable (to indicate) and clickable (to select) the whole row/col they refer to. 

Possibly add a 'whole font' or family-name labbel to the top left space that is empty to '(de)select all' :) In the case of all deselected, the API default instance would be still shown on/blue, though. 

As for the type tester, I am not sure the sidebar is good...

https://dinamodarkroom.com/gauntlet/ has range restrictor knobs on its sliders, and play buttons, and I think that is very effective at allowing the user to select a subspace and then "play it" to see what is inside. https://videoproof.typenetwork.com/ also uses the "play" mechanism to tour the design space for proofing purposes. 

I haven't added any play controls to this very hastily made mock up, but, I do think that the sidebar of axes subspace selection controls seems duplicative with the axes instance controls on the type-tester canvas and I wonder that a more on-canvas experience, with range restrictor knobs, is a better way to go. 

<img width="1440" alt="79000553-d8823700-7b1a-11ea-9eb3-918fec75fa89" src="https://user-images.githubusercontent.com/261579/79031749-0729fd00-7b6f-11ea-9f94-920af112790c.png">

I want to list out a few thing I did here...

* a mode switch to toggle between pins and ranges
* pins
  * have a single blue position knobs to show both current instance position, and pin selection value; this can be dragged continuously along the axis
  * have a grey axis track to show there is no rangee
* ranges
  * have a single blue position knob/dot that only shows current instance position
  * have min/max knobs `<` & `>` that can be dragged continuously to show range selection value. (Since slant and cursive can't be subset, they don't exist there)
* axes
  * have 'pegs' to show where filesize significant jumps are along an axis, meaning masters (imagining there are more along the weight axis) and rvrn substitutions (imagining there are a bunch of 'stops' along the cursive axis; although that implies it should have min/max knobs ;)

And a few things I did NOT do here, but should have ;) ...

...the file size estimate box shown in your earlier mocks, that responds to pin/range toggles and min/max reduction, is missing, and this is critical to the 'pegs' being useful.

...Probably the min/max knobs should be much heavier than I drew them above, to show they are as draggabble as the roundel position knobs.

...Something missing from the above is the specified range values, eg weight is `300..800` in the API, and that should be shown, perhaps to the right of the pin/range toggle button, and in blue. Then both those values and the blue current-instance-location values on the left should be blue and editable inputs, to set the values precisely. (Then I think its more clear that they grey values to the left and right of the sliders are the min/max axis range values, and are not editable.)

...A small error I see is that I forgot to color the min/max pegs of the cursive axis blue, oops.

OK! Now a big digression :) 

Today, the GF API returns a whole axis if you choose a point, or a range. However, this is exactly the sort of behavior that shouldn't be counted on, because the narrower the API URL specification given, the more ability the API has to optimize the filesize of what is returned by reducing the design space. https://developers.google.com/fonts/docs/css2#optimizing_for_latency_and_file_size says,

> **Be precise about the styles you are using.** The API delivers the requested styles in the most compact set of fonts. Requesting unused styles may cause your users to download more font data than they need, causing more latency. ... If you use a continuous range of weights, specify that weight range in your request.

The ideal API request specifies the actual range used on the page, and not a wider range than that. 

The underlying API subsetting mechanism is in fonttools' `instancer.py` and - as of the time I write this - the code comments explain there are 4 levels of design space reduction capability (https://github.com/fonttools/fonttools/blob/af2220b1b2b61a566c0eaad8ea8e39ac367ea24a/Lib/fontTools/varLib/instancer.py#L54-L61):

> The module currently supports only the first three "levels" of partial instancing, with the rest planned to be implemented in the future, namely:
> 
> L1) dropping one or more axes while leaving the default tables unmodified;
>
> L2) dropping one or more axes while pinning them at non-default locations;
>
> L3) restricting the range of variation of one or more axes, by setting either a new minimum or maximum, potentially -- though not necessarily -- dropping entire regions of variations that fall completely outside this new range.
>
> L4) moving the default location of an axis.

A full L4 instancer will reconstruct design spaces, and its possible that a subspace specified by the user as say wght 300..400 might be more efficient with a reconstructed 400 master so that the font returned is as requested 300..400, rather than returning the 300..800 range that is returned by an L3 instancer.

So! 

Returning to my mock, on the weight axis, I show the axis rail itself as blue within the min/max selection range, and grey on the unselected range on the upper/right end of the rail. This is what I'd expect with L4 instancing; precision. 

However, that kind of assumes this page has some foreknowledge of any API L4 instancing heuristics, and it won't, and currently they aren't implemented anyway... So, I propose and what is not shown above is that while the user can freely move the min/max selection range knobs, they would "light up" the rail only between pegs; and then in the actual design space of Recursive, there are only 1 peg on each of the Weight and Cursive axes, and therefore instead of foreknowledge of any API L4 instancing heuristics, a simple lookup table of discrete instance filesize possibilities can be deduced using `fonttools.instancer` for the combinatoral set of contiguous peg combinations. 

Which is to say that moving the min/max selection range knobs inside the range 300..800 will not show any changes to the filesize value estimate presented, nor the rail segment coloring; but it will update the API code on the right 'checkout' sidebar (as I mocked above) and in the range values I described as shown on the right of the pin/range toggles.

**Comment by davelab6** [comment]
https://twitter.com/shadihamid/status/1248664536078483462?s=19 shows a range selector with colored track

**Comment by arrowtype** [comment]
Hey Dave, thanks so much for taking the time to think through this and write down your thoughts!

I need to mockup these possibilities and general user flows before being able to respond very precisely, but I will make that work one of my goals for this week.

**Comment by arrowtype** [comment]
Later designs, for the record:

Ranges should be opt-in, allowing users to select a location to "freeze" or a custom range for each axis:

<img width="1440" alt="recursive-gf_api_config-2019_12_06--ranges" src="https://user-images.githubusercontent.com/45946693/88483352-43724500-cf35-11ea-940d-412df22302ef.png">

An instances view would be an important addition or alternative:

<img width="1440" alt="recursive-gf_api_config-2019_12_06-instances" src="https://user-images.githubusercontent.com/45946693/88483714-b11f7080-cf37-11ea-9af8-442ce9382508.png">

Generally, clicking an instance would add it to the embed URL. This would be a useful alternative way to help people select just the styles they need. A tricky thing would be getting the interaction between range & instance selection right, and making it clear to the user. The Google Fonts API would allow (I think?) for a mix of these approaches, but probably to keep things simple enough for users, we would have to present it as an either/or choice.

**Comment by arrowtype** [comment]
Closing this because a basic GF API config was added to the site, under the "Get Recursive" button. I would still love for there to be an "ultimate" experience for advanced API configuration – ideally on the Google Fonts site itself or else on a supplemental site – but that would realistically need to be a team effort, financed with at least a designer & JavaScript dev to collaborate on it.
